=== jmtomeX/Desarrollo-web-en-entorno-cliente/XML/xml_excell/schema_profesiones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Trabajadores">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="Trabajador" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Trabajador">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element name="Ciiudad" type="xs:string"/>
        <xs:element name="Provincia" type="xs:string"/>
        <xs:element name="Edad" type="xs:string"/>
          <xs:element name="Ocupacion" type="xs:string"/>
        <xs:element name="Fecha" type="xs:string"/>
        <xs:element name="Ingresos" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jmtomeX/Desarrollo-web-en-entorno-cliente/XML/xml_excell/profesiones_0.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Trabajadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///Z:/DAW%20Segundo/Desarrollo%20web%20en%20entorno%20cliente/XML/schema_profesiones.xsd">
	
<Trabajador>
<Nombre>María</Nombre>
	<Ciiudad>Donosti</Ciiudad>
	<Provincia>Gipuzkoa</Provincia>
	<Edad>34</Edad>
	<Ocupacion>Pintor</Ocupacion>
	<Fecha>03/06/2016</Fecha>
	<Ingresos>47000</Ingresos>
	</Trabajador>
		
	<Trabajador>	
	<Nombre>Ángel</Nombre>
	<Ciiudad>Bilbao</Ciiudad>
	<Provincia>Bizkaia</Provincia>
	<Edad>34</Edad>
	<Ocupacion>Pintor</Ocupacion>
	<Fecha>03/06/2016</Fecha>
	<Ingresos>47000</Ingresos>
	</Trabajador>Trabajador>	
</Trabajadores>
