=== jmtomeX/Desarrollo-web-en-entorno-cliente/Examen_DWEC/pedidos.dtd
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (cantidad+, fecha+)>
<!ATTLIST  pedido producto  (Portatil | Sobremesa | Tablet)  #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== jmtomeX/Desarrollo-web-en-entorno-cliente/Examen_DWEC/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "file:///Z:/DAW%20Segundo/Desarrollo%20web%20en%20entorno%20cliente/Examen_DWEC/pedidos.dtd">
<pedidos>
<pedido producto="Sobremesa">
<cantidad>4</cantidad>
<fecha>4/12/2019 </fecha>
</pedido>
<pedido producto="Portatil">
<cantidad>6</cantidad>
<fecha>4/12/2019 </fecha>
</pedido>
<pedido producto="Portatil">
<cantidad>6</cantidad>
<fecha>4/12/2019 </fecha>
</pedido>
<pedido producto="Portatil">
<cantidad>6</cantidad>
<fecha>7/12/2019 </fecha>
</pedido>
<pedido producto="Sobremesa">
<cantidad>6</cantidad>
<fecha>3/2/2019 </fecha>
</pedido>
<pedido producto="Tablet">
<cantidad>6</cantidad>
<fecha>15/10/2019 </fecha>
</pedido>
</pedidos>
