=== jmtomeX/Desarrollo-web-en-entorno-cliente/Examen_DWEC/ejer3/pedidos.dtd
<!--<!ELEMENT pedidos (productos+)>
<!ELEMENT productos (sobremesa|portatil|tablet)+ #REQUIRED >
<!ATTLIST productos fecha CDATA #REQUIRED>
 <!ATTLIST lineapedido cantidad CDATA>-->
 
<!ELEMENT pedidos (productos+)>
<!ELEMENT productos ( sobremesa | portatil | tablet)+>
<!ATTLIST productos fecha CDATA #REQUIRED>
<!ELEMENT sobremesa (#PCDATA)>
<!ATTLIST sobremesa cantidad CDATA #REQUIRED>
<!ELEMENT portatil (#PCDATA)>
<!ATTLIST portatil cantidad CDATA #REQUIRED>
<!ELEMENT tablet (#PCDATA)>
<!ATTLIST tablet cantidad CDATA #REQUIRED>

=== jmtomeX/Desarrollo-web-en-entorno-cliente/Examen_DWEC/ejer3/pedidos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pedidos SYSTEM "file:///D:/Desarrollo%20Aplicaciones%20WEB%202018/Desarrollo-web-en-entorno-cliente/Desarrollo-web-en-entorno-cliente/Examen_DWEC/ejer3/pedidos.dtd">
<pedidos>
    <productos fecha="4/12/2019">
      <sobremesa cantidad="4">sobremesa</sobremesa>
      <portatil cantidad="6">portatil</portatil>
      <tablet cantidad="4">tablet</tablet>
    </productos>
    <productos fecha="7/12/2019">
      <portatil cantidad="3">portatil</portatil>
      <tablet cantidad="2">tablet</tablet>
    </productos>
    <productos fecha="3/2/2019">
      <sobremesa cantidad="9" >sobremesa</sobremesa>
      <tablet cantidad="15" >tablet</tablet>
    </productos>
</pedidos>
